apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP # groups all pods under single ip
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: frontend
    app: nginx-app
