apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: id-1
    fsType: ext1
#  hostPath:
#    path: /tmp/dir