apiVersion: v1
kind: Service
metadata:
    name: myapp-service
spec:
    type: NodePort
    ports:
        - targetPort: 80
          port: 80
          nodePort: 30008 # must be in range 30000 - 32767
    selector:
        type: frontend
        app: nginx-app
