apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    type: frontend
    app: nginx-app
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
          - containerPort: 8080
      envFrom:
          - configMapRef:
                name: nginx-config
          - secretRef:
                name: nginx-secret
