apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    type: frontend
    app: nginx-app
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["MAX_ADMIN"]
      envFrom:
        - configMapRef:
            name: nginx-config
        - secretRef:
            name: nginx-secret
      resources:
        requests:
          memory: 1Gi
          cpu: 1
        limits:
          memory: 2Gi
          cpu: 2
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
  nodeSelector:
      size: Large # node label
  affinity:
      nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: size
                      operator: In
                      values:
                        - "Large"
