apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    type: frontend
    app: nginx-app
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      securityContext:
        runAsUser: user
        capabilities:
          add:
            - MAX_ADMIN
      envFrom:
        - configMapRef:
            name: nginx-config
        - secretRef:
            name: nginx-secret
