apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: math-add
        image: ubuntu
        command: ["expr", "21", "*", "2"]